import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import {createWorldContent} from '../server/world-content.mjs';
import {createQuestZones} from '../server/zones.mjs';
import {hubData} from '../server/hubs.mjs';
import {combatData} from '../server/combat.mjs';
const npc={id:'guide_npc',name:'Guide',description:'A friendly guide',dialogue:[{id:'hello',text:'Welcome!',next:'close',actions:[]}],quests:[]};
const quest=(extra={})=>({id:'first_quest',name:'First quest',description:'Explore together',givers:['guide_npc'],turn_in:{mode:'journal'},stages:[{id:'start',name:'Explore',objectives:[{id:'arrive',type:'visit',target:'honeydew-lantern',count:1}],next:'complete'}],rewards:{xp:5,coins:10,rpp:3,stats:{cha:1}},...extra});
function fixture(){const db=new DatabaseSync(':memory:'),live=createWorldContent(db,{spells:combatData.spells,equipment:hubData.equipment}),paid=[];let time=Date.parse('2026-09-19T12:00:00Z'),api,c,last;
 const start=()=>api=createQuestZones(db,{live,now:()=>time,roll:()=>0,grant:()=>({owner:'alice',id:'grant',client:'lidollquest'}),wallet:()=>({coins:0}),adjust:(...args)=>paid.push(args),diveOptions:{log:()=>{}}});start();
 const command=(action,extra={})=>({action,controller:'control',request_id:randomUUID(),character_id:c?.id,revision:c?.revision,...extra});
 const send=input=>{if(input.quest&&!input.quest_revision){const data=api.read('',c.id).onlineQuests;input.quest_revision=(input.action==='quest_accept'?[...data.available,...data.instances]:[...data.instances,...data.available]).find(q=>(q.quest??q.id)===input.quest)?.revision;}last=api.act('',input);c=last.character;return last;};const act=(action,extra)=>send(command(action,extra));
 const publish=(kind,entry)=>live.change({action:'content_publish',kind,id:entry.id,revision:(live.view()[kind==='npc'?'npcs':'quests'].find(r=>r.id===entry.id)?.revision??0),entry},'dm');
 act('create',{name:'Alice'});act('enter',{zone:'honeydew-lantern',content_version:1,quest_version:1,combat_version:3,loadout:{player_info:{cha:2,playerHealth:20,playerHealthMax:20,level:1,xp:0},inventory:[],player_spells:[]}});
 publish('npc',npc);
 return {db,live,paid,publish,command,send,act,get api(){return api;},get c(){return c;},get last(){return last;},advance(ms){time+=ms;},restart(){api.close();start();c=api.read('',c.id).character;},close(){api.close();db.close();}};
}
function acceptQuest(f,input){ // Drive a real NPC conversation for generic quest-behavior tests.
 const d=f.live.published().quests[input.quest],giver=d.givers[0]||d.turn_in.npc,zone='honeydew-lantern';let map=f.api.world.map(zone),p=map.placements.find(p=>p.kind==='npc'&&p.content===giver),temporary=false;
 if(!p){map=place(f,'npc',giver);p=map.placements.find(p=>p.content===giver);temporary=true;}
 beside(f,p);f.act('npc_talk',{placement:p.id,edition:map.edition});let talk=f.last.onlineQuests.conversation;
 const choose=label=>{talk=f.last.onlineQuests.conversation;const choice=talk.choices.find(c=>c.label===label);assert.ok(choice,'Missing conversation choice '+label);f.act('npc_choice',{conversation:talk.id,page:talk.page,choice:choice.index});};
 if(talk.choices.some(c=>c.label==='Ask about quests')){choose('Ask about quests');talk=f.last.onlineQuests.conversation;const stored=JSON.parse(f.db.prepare('SELECT definition FROM online_conversations WHERE character_id=?').get(f.c.id).definition),index=stored.dialogue.find(p=>p.id===talk.page).actions.findIndex(a=>a.next==='_offer_'+input.quest);assert.ok(index>=0,'This quest is already active or is not available again yet.');f.act('npc_choice',{conversation:talk.id,page:talk.page,choice:index});}else assert.fail('This quest is already active or is not available again yet.');
 const accept=f.last.onlineQuests.conversation.choices.find(c=>/^(Accept|Resume) quest$/.test(c.label));const command=f.command('npc_choice',{conversation:f.last.onlineQuests.conversation.id,page:f.last.onlineQuests.conversation.page,choice:accept.index});const result=f.send(command);
 if(temporary&&d.turn_in.mode==='journal'&&!d.stages.some(stage=>stage.objectives.some(o=>o.target===giver||o.npc===giver))){const current=f.api.world.map(zone);f.api.world.act({action:'world_remove_content',zone,edition:current.edition,revision:current.revision,placement:p.id});}
 return result;
}
test('quest publication, acceptance, progression and capped claim are durable and exactly once',()=>{const f=fixture();try{
 f.publish('quest',quest());const accepted=acceptQuest(f,{quest:'first_quest'});assert.equal(accepted.onlineQuests.instances[0].status,'ready');
 const command=f.command('quest_claim',{quest:'first_quest'});f.send(command);f.send(command);assert.equal(f.paid.length,1);assert.equal(f.c.loadout.player_info.cha,3);assert.equal(f.db.prepare('SELECT balance FROM quest_rpp_wallets').get().balance,3);
 f.restart();assert.throws(()=>acceptQuest(f,{quest:'first_quest'}),/not available again/);assert.equal(f.api.read('',f.c.id).onlineQuests.instances[0].status,'claimed');
 }finally{f.close();}});
test('NPC drafts, references, conflict, history and retirement preserve published content',()=>{const f=fixture();try{let row=f.publish('npc',npc);assert.equal(f.live.published().npcs.guide_npc.name,'Guide');assert.throws(()=>f.live.change({kind:'npc',id:npc.id,action:'content_save',revision:0,entry:npc},'dm'),/changed/);row=f.publish('npc',{...npc,name:'Changed',retired:true});assert.equal(f.live.published().npcs.guide_npc.retired,true);f.live.change({kind:'npc',id:npc.id,action:'content_rollback',revision:row.revision,target_revision:1},'dm');assert.equal(f.live.published().npcs.guide_npc.name,'Guide');assert.throws(()=>f.publish('npc',{...npc,quests:['missing_quest']}),/referenced quest/);assert.throws(()=>f.publish('quest',quest({stages:[{id:'loop',objectives:[{id:'wait',type:'timer'}],next:'loop'}]})),/cycle/);}finally{f.close();}});
test('accepted definitions pin rewards and branching; abandoning cannot restart the timer',()=>{const f=fixture();try{f.publish('quest',quest({timer:{seconds:60,mode:'online'},stages:[{id:'start',objectives:[{id:'wait',type:'timer',count:20}],branches:[{id:'good',label:'Finish',to:'complete',conditions:[]}]}]}));acceptQuest(f,{quest:'first_quest'});f.advance(10000);f.act('heartbeat');f.api.tick();f.act('quest_abandon',{quest:'first_quest'});f.publish('quest',quest({rewards:{coins:999}}));acceptQuest(f,{quest:'first_quest'});f.advance(11000);f.act('heartbeat');f.api.tick();const q=f.api.read('',f.c.id).onlineQuests.instances[0];assert.equal(q.status,'choice');assert.equal(q.rewards.coins,10);f.act('quest_branch',{quest:'first_quest',branch:'good'});assert.equal(f.last.onlineQuests.instances[0].status,'ready');}finally{f.close();}});
test('managed placements reject stale maps and blocked tiles; conversations validate position and pages',()=>{const f=fixture();try{f.publish('npc',npc);let map=f.api.world.map('honeydew-lantern');assert.throws(()=>f.api.world.act({action:'world_place_content',zone:map.id,edition:map.edition,revision:map.revision,placement_kind:'npc',content:npc.id,x:0,y:0}),/reachable tile/);let placed;
 for(let y=2;y<map.floor.height-2&&!placed;y++)for(let x=2;x<map.floor.width-2&&!placed;x++)try{placed=f.api.world.act({action:'world_place_content',zone:map.id,edition:map.edition,revision:map.revision,placement_kind:'npc',content:npc.id,x,y});}catch(e){if(!/reachable tile/.test(e.message))throw e;}
 assert.ok(placed);const p=placed.placements[0];assert.throws(()=>f.api.world.act({action:'world_remove_content',zone:map.id,edition:map.edition,revision:map.revision,placement:p.id}),/map changed/);
 f.db.prepare('UPDATE quest_presence SET x=?,y=? WHERE character_id=?').run(p.x+1,p.y,f.c.id);f.act('npc_talk',{placement:p.id,edition:map.edition});const talk=f.last.onlineQuests.conversation;assert.equal(talk.text,'Welcome!');assert.throws(()=>f.act('npc_choice',{conversation:talk.id,page:'stale',choice:-1}),/page changed/);f.act('npc_choice',{conversation:talk.id,page:'hello',choice:-1});assert.equal(f.last.onlineQuests.conversation.ended,true);
 const floor=structuredClone(placed.floor);floor.walls[p.y][p.x]=1;const relocated=f.api.quests.placements.realize(map.id,'replacement',floor);assert.ok(relocated[0].x!==p.x||relocated[0].y!==p.y);f.restart();assert.equal(f.api.world.map(map.id).placements[0].id,p.id);
 }finally{f.close();}});

function place(f,kind,content,lifetime='persistent',zone='honeydew-lantern',extra={}){const map=f.api.world.map(zone);for(let y=2;y<map.floor.height-2;y++)for(let x=2;x<map.floor.width-2;x++)try{return f.api.world.act({action:'world_place_content',zone,edition:map.edition,revision:map.revision,placement_kind:kind,content,x,y,lifetime,...extra});}catch(e){if(!/reachable tile/.test(e.message))throw e;}throw Error('No placement');}
function beside(f,p){f.db.prepare('UPDATE quest_presence SET x=?,y=? WHERE character_id=?').run(p.x+1,p.y,f.c.id);}
test('quest tokens are personal, non-farmable and consumed once by explicit delivery',()=>{const f=fixture();try{
 f.publish('npc',npc);const n=place(f,'npc',npc.id).placements[0],map=place(f,'token','parcel'),token=map.placements.find(p=>p.kind==='token');
 f.publish('quest',quest({stages:[{id:'collecting',objectives:[{id:'parcel',type:'collect',target:'parcel',token:true}],next:'delivery'},{id:'delivery',objectives:[{id:'hand_over',type:'deliver',target:'parcel',token:true,npc:npc.id}],next:'complete'}]}));acceptQuest(f,{quest:'first_quest'});
 beside(f,token);f.act('quest_interact',{placement:token.id,edition:map.edition});f.act('quest_interact',{placement:token.id,edition:map.edition});assert.equal(f.last.onlineQuests.instances[0].stage,'delivery');
 beside(f,n);f.act('npc_talk',{placement:n.id,edition:map.edition});const conversation=f.last.onlineQuests.conversation.id;f.act('quest_deliver',{quest:'first_quest',objective:'hand_over',conversation});assert.equal(f.last.onlineQuests.instances[0].status,'ready');const stored=JSON.parse(f.db.prepare('SELECT state FROM online_quests').get().state);assert.equal(stored.tokens.parcel,0);assert.throws(()=>f.act('quest_deliver',{quest:'first_quest',objective:'hand_over',conversation}),/not active/);
 }finally{f.close();}});
test('state, equipment, inventory and timer predicates evaluate committed character state',()=>{const f=fixture();try{
 const item=Object.keys(hubData.equipment)[0];f.publish('quest',quest({stages:[{id:'conditions',objectives:[{id:'state',type:'state',field:'shame',op:'gte',value:2},{id:'gear',type:'equipment',slot:'head',target:item},{id:'inventory',type:'collect',target:item}],next:'complete'}]}));acceptQuest(f,{quest:'first_quest'});assert.equal(f.last.onlineQuests.instances[0].status,'active');const loadout=structuredClone(f.c.loadout);loadout.player_info.shame=3;loadout.player_info.equipped_head=item;loadout.inventory.push(structuredClone(hubData.equipment[item]));f.act('loadout',{loadout});assert.equal(f.last.onlineQuests.instances[0].status,'ready');
 }finally{f.close();}});
test('inventory overflow keeps rewards pending; caps and spell unlocks survive claim retries',()=>{const f=fixture();try{
 const item=Object.keys(hubData.equipment)[0],spell=Object.keys(combatData.spells)[0];f.publish('quest',quest({rewards:{coins:1000000,items:[{id:item,count:1}],spells:[spell]}}));acceptQuest(f,{quest:'first_quest'});const full=structuredClone(f.c.loadout);full.inventory=Array.from({length:hubData.config.inventory_capacity},()=>structuredClone(hubData.equipment[item]));f.act('loadout',{loadout:full});assert.throws(()=>f.act('quest_claim',{quest:'first_quest'}),/Make room/);assert.equal(f.paid.length,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM online_quest_claims').get().n,0);full.inventory=[];f.act('loadout',{loadout:full});f.act('quest_claim',{quest:'first_quest'});assert.ok(f.last.onlineQuests.instances[0].reward.cappedCoins>0);assert.ok(f.c.loadout.player_spells.includes(spell));assert.equal(f.c.loadout.inventory.length,1);const old=structuredClone(f.c.loadout);old.player_spells=[];f.act('loadout',{loadout:old});assert.ok(f.c.loadout.player_spells.includes(spell));
 }finally{f.close();}});
test('online clocks pause after presence expires and across restart; real-time deadlines do not',()=>{const f=fixture();try{
 for(const mode of ['online','realtime'])f.publish('quest',quest({id:'clock_'+mode,timer:{mode,seconds:40},stages:[{id:'waiting',objectives:[{id:'wait',type:'timer',count:100}],next:'complete'}]}));for(const mode of ['online','realtime'])acceptQuest(f,{quest:'clock_'+mode});f.advance(30000);f.api.tick();f.advance(60000);f.restart();f.api.tick();const states=f.api.read('',f.c.id).onlineQuests.instances;assert.equal(states.find(q=>q.quest==='clock_online').status,'active');assert.equal(states.find(q=>q.quest==='clock_realtime').status,'failed');
 }finally{f.close();}});
test('repeat policies use claim time, and accepted reward revisions survive publication and rollback',()=>{const f=fixture();try{
 f.publish('quest',quest({repeat:'cooldown',cooldown_seconds:2}));acceptQuest(f,{quest:'first_quest'});f.act('quest_claim',{quest:'first_quest'});assert.throws(()=>acceptQuest(f,{quest:'first_quest'}),/not available again/);f.advance(2100);acceptQuest(f,{quest:'first_quest'});f.publish('quest',quest({repeat:'cooldown',cooldown_seconds:2,rewards:{coins:99}}));assert.equal(f.last.onlineQuests.instances.find(q=>q.status==='ready').rewards.coins,10);f.act('quest_claim',{quest:'first_quest'});assert.equal(f.paid.length,2);
 }finally{f.close();}});
test('party event credit requires proximity and per-objective opt-in; kill events remain encounter-scoped',()=>{const f=fixture();try{f.publish('npc',npc);
 f.publish('quest',quest({stages:[{id:'talking',objectives:[{id:'chat',type:'talk',target:npc.id,sharing:'party'}],next:'complete'}]}));acceptQuest(f,{quest:'first_quest'});const original=f.db.prepare('SELECT * FROM online_quests').get(),other='other-character';f.db.prepare('INSERT INTO quest_characters VALUES (?,?,?,?,?,?,?)').run(other,'bob','Bob',0,0,JSON.stringify(f.c),'bob-create');f.db.prepare('INSERT INTO online_quests VALUES (?,?,?,?,?,?,?)').run('other-quest',other,original.quest,original.revision,original.definition,original.state,original.created);const p=f.db.prepare('SELECT * FROM quest_presence').get();f.db.prepare('INSERT INTO quest_presence(owner,character_id,zone,grant_id,controller,x,y,seen,moved) VALUES (?,?,?,?,?,?,?,?,?)').run('bob',other,p.zone,'bob','bob',p.x+8,p.y,p.seen,p.moved);f.db.prepare('INSERT INTO quest_parties VALUES (?,?,?)').run('party',f.c.id,0);for(const id of [f.c.id,other])f.db.prepare('INSERT INTO quest_party_members VALUES (?,?,?)').run(id,'party',0);
 f.api.quests.event(f.c,f.c,{id:'talk-event',type:'talk',target:npc.id});assert.equal(JSON.parse(f.db.prepare('SELECT state FROM online_quests WHERE id=?').get('other-quest').state).status,'ready');
 const reset=JSON.parse(original.state);f.db.prepare('UPDATE online_quests SET state=? WHERE id=?').run(JSON.stringify(reset),'other-quest');f.db.prepare('UPDATE quest_presence SET x=x+1 WHERE character_id=?').run(other);f.api.quests.event(f.c,f.c,{id:'far-talk',type:'talk',target:npc.id});assert.equal(JSON.parse(f.db.prepare('SELECT state FROM online_quests WHERE id=?').get('other-quest').state).status,'active');
 }finally{f.close();}});
test('required placements block removal, temporary placements expire, and invalid replacement geometry is rejected',()=>{const f=fixture();try{
 f.publish('npc',npc);const map=place(f,'npc',npc.id),p=map.placements[0];f.publish('quest',quest({stages:[{id:'talking',objectives:[{id:'chat',type:'talk',target:npc.id}],next:'complete'}]}));acceptQuest(f,{quest:'first_quest'});assert.throws(()=>f.api.world.act({action:'world_remove_content',zone:map.id,revision:map.revision,edition:map.edition,placement:p.id}),/Active quests depend/);
 const temporary=place(f,'token','temporary_token','temporary'),frozen=structuredClone(temporary.floor);assert.equal(f.api.quests.placements.realize(map.id,'next-map',frozen).length,1);frozen.walls=frozen.walls.map(row=>row.map(()=>1));assert.throws(()=>f.api.quests.placements.realize(map.id,'invalid-map',frozen),/No reachable tile/);const latest=f.api.world.map(map.id);f.api.world.act({action:'world_remove_content',zone:map.id,revision:latest.revision,edition:latest.edition,placement:p.id,resolution:'fail'});assert.equal(f.api.read('',f.c.id).onlineQuests.instances[0].status,'failed');
 }finally{f.close();}});

test('Dive regeneration realizes persistent NPCs, expires temporary objects and keeps the old map after placement failure',async()=>{const f=fixture();try{
 f.publish('npc',npc);const zone='dive-quarters';place(f,'npc',npc.id,'persistent',zone);place(f,'token','one_map_token','temporary',zone);let map=f.api.world.map(zone),old=map.edition;
 f.api.world.act({action:'world_regenerate',zone,edition:map.edition,revision:map.revision,confirm_reset_rewards:true});f.restart();f.api.tick();await new Promise(r=>setImmediate(r));f.advance(1100);f.api.tick();map=f.api.world.map(zone);assert.notEqual(map.edition,old);assert.equal(map.placements.length,1);assert.equal(map.placements[0].content,npc.id);
 old=map.edition;f.api.world.act({action:'world_regenerate',zone,edition:map.edition,revision:map.revision,confirm_reset_rewards:true});f.advance(1100);f.api.tick();await new Promise(r=>setImmediate(r));const job=f.db.prepare("SELECT * FROM world_regeneration WHERE status='draining'").get();assert.ok(job);const broken=JSON.parse(job.candidate);broken.walls=broken.walls.map(row=>row.map(()=>1));f.db.prepare('UPDATE world_regeneration SET candidate=? WHERE id=?').run(JSON.stringify(broken),job.id);f.advance(1100);f.api.tick();map=f.api.world.map(zone);assert.equal(map.edition,old);assert.equal(map.lastJob.status,'failed');assert.match(map.lastJob.error,/No reachable tile/);
 }finally{f.close();}});
test('NPC publication validates references, retired dependencies and old-client entry is gated',()=>{const f=fixture();try{
 assert.throws(()=>f.publish('quest',quest({turn_in:{mode:'npc',npc:'missing_npc'}})),/referenced NPC/);f.publish('npc',npc);f.publish('quest',quest({givers:[npc.id]}));assert.throws(()=>f.publish('npc',{...npc,retired:true}),/referencing/);assert.throws(()=>f.act('enter',{zone:'honeydew-lantern',content_version:1,combat_version:3}),/Update the game/);assert.throws(()=>f.api.questRead('', 'someone-elses-character','first_quest'),/not found for this account/);
 }finally{f.close();}});
test('UTC daily and weekly eligibility opens only after the claim period ends',()=>{const f=fixture();try{
 for(const repeat of ['daily','weekly'])f.publish('quest',quest({id:'repeat_'+repeat,repeat}));for(const repeat of ['daily','weekly']){acceptQuest(f,{quest:'repeat_'+repeat});f.act('quest_claim',{quest:'repeat_'+repeat});assert.throws(()=>acceptQuest(f,{quest:'repeat_'+repeat}),/not available again/);}
 f.advance(8*86400000);f.act('enter',{zone:'honeydew-lantern',content_version:1,quest_version:1,combat_version:3,loadout:f.c.loadout});for(const repeat of ['daily','weekly'])acceptQuest(f,{quest:'repeat_'+repeat});assert.equal(f.last.onlineQuests.instances.filter(q=>q.status==='ready').length,2);
 }finally{f.close();}});

test('equipment and state predicates must still hold when the remaining objectives finish',()=>{const f=fixture();try{
 const item=Object.keys(hubData.equipment)[0];f.publish('quest',quest({stages:[{id:'checks',objectives:[{id:'gear',type:'equipment',target:item,slot:'head'},{id:'condition',type:'state',field:'shame',value:2},{id:'clock',type:'timer',count:5}],next:'complete'}]}));acceptQuest(f,{quest:'first_quest'});const gear=structuredClone(f.c.loadout);gear.player_info.equipped_head=item;gear.player_info.shame=3;f.act('loadout',{loadout:gear});assert.equal(f.last.onlineQuests.instances[0].objectives[0].progress,1);gear.player_info.equipped_head='';gear.player_info.shame=0;f.act('loadout',{loadout:gear});f.advance(6000);f.api.tick();const q=f.api.read('',f.c.id).onlineQuests.instances[0];assert.equal(q.status,'active');assert.equal(q.objectives[0].progress,0);assert.equal(q.objectives[1].progress,0);
 }finally{f.close();}});

test('abandoned retired quests resume their exact accepted NPC and reward definitions',()=>{const f=fixture();try{
 f.publish('npc',npc);const map=place(f,'npc',npc.id),p=map.placements[0];f.publish('quest',quest({stages:[{id:'talking',objectives:[{id:'chat',type:'talk',target:npc.id}],next:'complete'}]}));acceptQuest(f,{quest:'first_quest'});const pinned=f.db.prepare('SELECT revision,definition FROM online_quests').get();f.act('quest_abandon',{quest:'first_quest'});f.publish('quest',quest({retired:true}));f.publish('npc',{...npc,dialogue:[{id:'hello',text:'A changed NPC.',next:'close',actions:[]}]});acceptQuest(f,{quest:'first_quest'});assert.deepEqual(f.db.prepare('SELECT revision,definition FROM online_quests').get(),pinned);beside(f,p);f.act('npc_talk',{placement:p.id,edition:map.edition});assert.equal(f.last.onlineQuests.conversation.text,'Welcome!');
 }finally{f.close();}});

test('map replacement cannot strand an active quest on an expiring objective',()=>{const f=fixture();try{
 const map=place(f,'token','required_token','temporary');f.publish('quest',quest({stages:[{id:'tokens',objectives:[{id:'gather',type:'collect',token:true,target:'required_token'}],next:'complete'}]}));acceptQuest(f,{quest:'first_quest'});assert.throws(()=>f.api.quests.placements.realize(map.id,'replacement',map.floor),/expiring placement/);place(f,'token','required_token');assert.equal(f.api.quests.placements.realize(map.id,'replacement',map.floor).length,1);
 }finally{f.close();}});

test('conversation offers disclose consequences and reject changed quest revisions',()=>{const f=fixture();try{
 f.publish('npc',npc);f.publish('quest',quest({givers:[npc.id]}));f.publish('npc',{...npc,dialogue:[{id:'hello',text:'Please help.',actions:[{label:'Accept',effect:'offer',quest:'first_quest',next:'close'}]}]});const map=place(f,'npc',npc.id),p=map.placements[0];beside(f,p);f.act('npc_talk',{placement:p.id,edition:map.edition});let talk=f.last.onlineQuests.conversation;assert.match(talk.text,/10 coins/);f.publish('quest',quest({givers:[npc.id],rewards:{coins:20}}));assert.throws(()=>f.act('npc_choice',{conversation:talk.id,page:talk.page,choice:0}),/quest changed/);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM online_quests').get().n,0);f.act('npc_talk',{placement:p.id,edition:map.edition});talk=f.last.onlineQuests.conversation;assert.match(talk.text,/20 coins/);f.act('npc_choice',{conversation:talk.id,page:talk.page,choice:0});assert.equal(f.last.onlineQuests.instances[0].status,'ready');
 }finally{f.close();}});

test('shared delivery consumes only the deliverer tokens and credits the matching nearby objective once',()=>{const f=fixture();try{
 f.publish('npc',npc);const map=place(f,'npc',npc.id),p=map.placements[0];f.publish('quest',quest({stages:[{id:'delivery',objectives:[{id:'parcel',type:'deliver',target:'parcel',token:true,npc:npc.id,sharing:'party'}],next:'complete'}]}));acceptQuest(f,{quest:'first_quest'});const original=f.db.prepare('SELECT * FROM online_quests').get(),state=JSON.parse(original.state);state.tokens.parcel=1;f.db.prepare('UPDATE online_quests SET state=? WHERE id=?').run(JSON.stringify(state),original.id);const other='delivery-friend';f.db.prepare('INSERT INTO quest_characters VALUES (?,?,?,?,?,?,?)').run(other,'bob','Bob',0,0,JSON.stringify(f.c),'bob-create');f.db.prepare('INSERT INTO online_quests VALUES (?,?,?,?,?,?,?)').run('friend-quest',other,original.quest,original.revision,original.definition,original.state,original.created);const pos=f.db.prepare('SELECT * FROM quest_presence').get();f.db.prepare('INSERT INTO quest_presence(owner,character_id,zone,grant_id,controller,x,y,seen,moved) VALUES (?,?,?,?,?,?,?,?,?)').run('bob',other,pos.zone,'bob','bob',p.x+2,p.y,pos.seen,pos.moved);f.db.prepare('INSERT INTO quest_parties VALUES (?,?,?)').run('delivery-party',f.c.id,0);for(const id of [f.c.id,other])f.db.prepare('INSERT INTO quest_party_members VALUES (?,?,?)').run(id,'delivery-party',0);beside(f,p);f.act('npc_talk',{placement:p.id,edition:map.edition});const command=f.command('quest_deliver',{quest:'first_quest',objective:'parcel',conversation:f.last.onlineQuests.conversation.id});f.send(command);f.send(command);const mine=JSON.parse(f.db.prepare('SELECT state FROM online_quests WHERE id=?').get(original.id).state),friend=JSON.parse(f.db.prepare('SELECT state FROM online_quests WHERE id=?').get('friend-quest').state);assert.equal(mine.tokens.parcel,0);assert.equal(friend.tokens.parcel,undefined);assert.equal(friend.status,'ready');
 }finally{f.close();}});

test('token and object artwork accepts shipped icons and immutable uploads, rejecting unknown references',()=>{const f=fixture();try{
 const icon='sprIcon_stamina_potion';assert.ok(f.live.view().compiledSprites.includes(icon));assert.ok(f.live.asset(icon).png);
 let map=place(f,'token','quest_parcel','persistent','honeydew-lantern',{sprite:icon});const token=map.placements.find(p=>p.content==='quest_parcel');assert.equal(token.sprite,icon);
 const asset=f.live.putAsset({png:'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAN0lEQVR4nO3QQREAMAgDQYofTCKxhspUBZ+NgcvsudUvFpebcQcIECBAgAABAgQIECBAgACBTzBf6ALAS4QDIwAAAABJRU5ErkJggg==',frames:1});map=place(f,'interact','quest_switch','persistent',map.id,{sprite:asset.id});assert.equal(map.placements.find(p=>p.content==='quest_switch').sprite,asset.id);
 for(const sprite of ['missing_sprite','managed-missing','https://invalid.test/image.png'])assert.throws(()=>place(f,'token','bad_sprite','persistent',map.id,{sprite}),/artwork|Artwork/);
 f.publish('npc',npc);assert.equal(f.api.read('',f.c.id).worldPlacements.find(p=>p.id===token.id).sprite,icon);f.restart();assert.equal(f.api.world.map(map.id).placements.find(p=>p.id===token.id).sprite,icon);assert.equal(f.api.quests.placements.realize(map.id,'replacement',map.floor).find(p=>p.content==='quest_switch').sprite,asset.id);
 }finally{f.close();}});

test('acceptance requires an offered dialogue choice beside the giver, with replay and restart protection',()=>{const f=fixture();try{
 f.publish('quest',quest());const map=place(f,'npc',npc.id),p=map.placements.find(p=>p.content===npc.id);assert.deepEqual(f.api.read('',f.c.id).onlineQuests.available,[]);assert.throws(()=>f.act('quest_accept',{quest:'first_quest'}),/Speak to the designated NPC/);beside(f,p);f.act('npc_talk',{placement:p.id,edition:map.edition});let t=f.last.onlineQuests.conversation;assert.throws(()=>f.act('quest_accept',{quest:'first_quest',conversation:t.id}),/Speak to the designated NPC/);
 const choose=label=>{t=f.api.read('',f.c.id).onlineQuests.conversation;const a=t.choices.find(a=>a.label===label&&a.available);assert.ok(a);return f.act('npc_choice',{conversation:t.id,page:t.page,choice:a.index});};choose('Ask about quests');choose('First quest');t=f.last.onlineQuests.conversation;const command=f.command('npc_choice',{conversation:t.id,page:t.page,choice:t.choices.find(c=>c.label==='Accept quest').index});
 f.db.prepare('UPDATE quest_presence SET x=x+12 WHERE character_id=?').run(f.c.id);assert.throws(()=>f.send(command),/Stand beside/);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM online_quests').get().n,0);beside(f,p);f.restart();f.send(command);f.send(command);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM online_quests').get().n,1);assert.deepEqual(f.last.onlineQuests.available,[]);
 }finally{f.close();}});

test('giver menus paginate without replacing original dialogue and enforce acceptance requirements',()=>{const f=fixture();try{
 f.publish('npc',{...npc,dialogue:[{id:'hello',text:'First page',next:'second',actions:[]},{id:'second',text:'Second page',next:'close',actions:[]}]});for(let i=0;i<8;i++)f.publish('quest',quest({id:'offer_'+i,name:'Offer '+i}));f.publish('quest',quest({id:'locked_offer',conditions:[{field:'shame',op:'gte',value:999}]}));assert.throws(()=>f.publish('quest',quest({id:'missing_giver',givers:[]})),/quest giver/);const map=place(f,'npc',npc.id),p=map.placements.find(p=>p.content===npc.id);beside(f,p);f.act('npc_talk',{placement:p.id,edition:map.edition});const choose=label=>{const t=f.last.onlineQuests.conversation,c=t.choices.find(c=>c.label===label);assert.ok(c);f.act('npc_choice',{conversation:t.id,page:t.page,choice:c.index});};choose('Continue');assert.equal(f.last.onlineQuests.conversation.text,'Second page');f.act('npc_talk',{placement:p.id,edition:map.edition});choose('Ask about quests');assert.equal(f.last.onlineQuests.conversation.choices.length,8);choose('More quests');assert.equal(f.last.onlineQuests.conversation.choices.length,3);choose('Offer 7');choose('Accept quest');assert.equal(f.last.onlineQuests.instances[0].quest,'offer_7');
 }finally{f.close();}});

test('legacy abandoned journal quests can resume at a newly assigned giver without changing accepted rewards',()=>{const f=fixture();try{
 f.publish('quest',quest({stages:[{id:'wait',objectives:[{id:'wait',type:'timer',count:60}],next:'complete'}]}));acceptQuest(f,{quest:'first_quest'});f.act('quest_abandon',{quest:'first_quest'});const row=f.db.prepare('SELECT * FROM online_quests').get(),definition=JSON.parse(row.definition);definition.givers=[];definition.npcs={};f.db.prepare('UPDATE online_quests SET definition=? WHERE id=?').run(JSON.stringify(definition),row.id);f.publish('quest',quest({rewards:{coins:99}}));acceptQuest(f,{quest:'first_quest'});const resumed=f.api.read('',f.c.id).onlineQuests.instances[0];assert.equal(resumed.rewards.coins,10);assert.equal(resumed.status,'active');assert.equal(resumed.stage,'wait');
 }finally{f.close();}});
