import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createStoryFlows} from '../server/story-flows.mjs';
import {validateFlow} from '../server/flow-content.mjs';
import {storyFlagsMatch,setStoryFlag} from '../server/story-flags.mjs';
const flag={id:'story_rescued',name:'Rescued the scout',description:''};
const n=(id,type,rest={})=>({id,type,...rest});
const e=(from,port,to)=>({from,port,to});
const story=()=>({id:'rescue',name:'Rescue',nodes:[n('entry','entry'),n('hello','dialogue',{text:'Will you help?'}),n('choice','choice',{text:'Choose.',choices:[{id:'yes',label:'Yes'},{id:'no',label:'No'}]}),n('fight','battle',{ref:'slime'}),n('flag','set_flag',{flag:flag.id}),n('prize','reward',{rewards:{xp:5,coins:10}}),n('end','end')],edges:[e('entry','next','hello'),e('hello','next','choice'),e('choice','yes','fight'),e('choice','no','end'),e('fight','victory','flag'),e('fight','defeat','end'),e('fight','retreat','end'),e('flag','next','prize'),e('prize','next','end')],bindings:[{kind:'npc',ref:'scout',entry:'entry'}]});
function fixture(){const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE quest_characters(id TEXT PRIMARY KEY,name TEXT,state TEXT,revision INTEGER)');let time=100;const c={id:'alice'},s={flowVersion:1,fullDungeon:{flags:{school_graduated:true}}};db.prepare('INSERT INTO quest_characters VALUES (?,?,?,?)').run(c.id,'Alice',JSON.stringify(s),0);const p={npcs:{scout:{id:'scout'}},monsters:{slime:{id:'slime'}},quests:{},orbs:{}};const live={published:()=>p,view:()=>({compiledSprites:[],assets:[],equipment:[]}),bundle:()=>{}};const calls=[],options={live,world:{catalog:()=>[]},enabled:true,now:()=>time++,adapters:{battle:()=>{calls.push('battle');s.run={id:'encounter'};return 'encounter';},reward:(c,s,n,d,r)=>calls.push(r)}};let flows=createStoryFlows(db,options);flows.gm({action:'flow_flag_save',entry:flag,revision:0},'gm');const publish=(entry=story(),revision=0)=>flows.gm({action:'flow_publish',id:entry.id,entry,revision},'gm');const choose=(choice='')=>{const v=flows.snapshot(c,s);flows.act(c,s,{flow_run:v.id,flow_step:v.step,choice});};return {db,c,s,calls,p,publish,choose,get flows(){return flows;},restart(){flows=createStoryFlows(db,options);},close(){db.close();}};}
test('false defaults and authored flags preserve engine-owned achievements',()=>{const state={fullDungeon:{flags:{school_graduated:true}}};assert.equal(storyFlagsMatch(state,{all:['story_rescued']}),false);assert.equal(storyFlagsMatch(state,{none:['story_rescued']}),true);setStoryFlag(state,flag.id,true,[flag]);assert.equal(storyFlagsMatch(state,{all:[flag.id],any:['missing',flag.id]}),true);setStoryFlag(state,flag.id,false,[flag]);assert.equal(state.fullDungeon.flags.school_graduated,true);assert.throws(()=>setStoryFlag(state,'school_graduated',false,[{id:'school_graduated'}]),/Engine/);});
test('validator rejects missing ports, forged flags, unknown links and automatic cycles',()=>{const s=story();s.edges.pop();assert.throws(()=>validateFlow(s,{flags:[flag],publish:true}),/Connect/);s.edges.push(e('prize','next','flag'));assert.throws(()=>validateFlow(s,{flags:[flag],publish:true}),/loop/);s.nodes.find(n=>n.id==='flag').flag='school_graduated';assert.throws(()=>validateFlow(s,{flags:[flag],publish:true}),/authored flag/);});
test('pinned flow survives publication/restart and settles battle and reward once',()=>{const f=fixture();try{f.publish();assert.equal(f.flows.start(f.c,f.s,'npc','scout'),true);const first=f.flows.snapshot(f.c,f.s);f.choose();assert.throws(()=>f.flows.act(f.c,f.s,{flow_run:first.id,flow_step:first.step}),/changed/);f.choose('yes');assert.deepEqual(f.calls,['battle']);const changed=story();changed.nodes.find(n=>n.id==='prize').rewards.coins=999;f.publish(changed,1);f.restart();f.flows.resume(f.c,f.s);assert.equal(f.calls.length,1);f.flows.settled(f.c,f.s,'wrong','win');f.s.run=null;f.flows.resume(f.c,f.s);assert.equal(f.calls.length,1);f.flows.settled(f.c,f.s,'encounter','win');f.s.pendingDefeat={};f.flows.resume(f.c,f.s);assert.equal(f.calls.length,1);delete f.s.pendingDefeat;f.flows.resume(f.c,f.s);assert.equal(f.s.fullDungeon.flags.story_rescued,true);assert.equal(f.calls.length,2);f.flows.resume(f.c,f.s);f.flows.settled(f.c,f.s,'encounter','win');assert.equal(f.calls.length,2);assert.equal(f.flows.start(f.c,f.s,'npc','scout'),false);}finally{f.close();}});
test('choices revalidate current flags without replacing an open page',()=>{const f=fixture();try{const d=story();d.nodes.find(n=>n.id==='choice').choices[0].conditions={all:[flag.id]};f.publish(d);f.flows.start(f.c,f.s,'npc','scout');f.choose();assert.throws(()=>f.choose('yes'),/no longer available/);f.s.fullDungeon.flags[flag.id]=true;f.choose('yes');assert.equal(f.calls[0],'battle');}finally{f.close();}});
test('preview has no side effects and flags remain private to each character',()=>{const f=fixture();try{f.publish();const preview=f.flows.gm({action:'flow_preview',entry:story(),node:'fight',outcome:'victory',flags:{}},'gm');assert.equal(preview.flags[flag.id],true);assert.equal(f.s.fullDungeon.flags[flag.id],undefined);assert.equal(f.calls.length,0);f.s.flowVersion=0;assert.throws(()=>f.flows.start(f.c,f.s,'npc','scout'),/Update/);f.s.flowVersion=1;f.flows.start(f.c,f.s,'npc','scout');assert.equal(f.flows.snapshot({id:'bob'},f.s),null);}finally{f.close();}});
test('defeat and retreat never award victory flags',()=>{for(const outcome of ['defeat','flee']){const f=fixture();try{f.publish();f.flows.start(f.c,f.s,'npc','scout');f.choose();f.choose('yes');f.flows.settled(f.c,f.s,'encounter',outcome);f.s.run=null;f.flows.resume(f.c,f.s);assert.equal(f.s.fullDungeon.flags[flag.id],undefined);assert.equal(f.calls.length,1);}finally{f.close();}}});

test('imported choice requirements reject undefined authored flags',()=>{const d=story();d.nodes.find(n=>n.id==='choice').choices[0].requirements=[{flags:{all:['story_missing']}}];assert.throws(()=>validateFlow(d,{flags:[flag],publish:true}),/Unknown story flag/);});

test('an open NPC offer cannot switch to a newly published story',()=>{const f=fixture();try{f.publish();const review=f.flows.review(f.c,f.s,'npc','scout');assert.ok(review);f.publish(story(),1);assert.throws(()=>f.flows.start(f.c,f.s,'npc','scout',review),/offer changed/);assert.equal(f.flows.active(f.c),null);}finally{f.close();}});

test('changed flag reaction invalidates an NPC offer without starting another branch',()=>{const f=fixture();try{f.p.npcs.scout.story_reactions=[{conditions:{all:[flag.id]},entry:'hello'}];f.publish();const review=f.flows.review(f.c,f.s,'npc','scout');f.s.fullDungeon.flags[flag.id]=true;assert.throws(()=>f.flows.start(f.c,f.s,'npc','scout',review),/offer changed/);assert.equal(f.flows.active(f.c),null);}finally{f.close();}});
