import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createStoryFlows} from '../server/story-flows.mjs';
import {flowFaithCatalog,pietyMatches} from '../server/flow-faith.mjs';
import {validateFlow} from '../server/flow-content.mjs';
import {storyFlagsMatch,setStoryFlag} from '../server/story-flags.mjs';
const flag={id:'story_rescued',name:'Rescued the scout',description:''};
const n=(id,type,rest={})=>({id,type,...rest});
const e=(from,port,to)=>({from,port,to});
const story=()=>({id:'rescue',name:'Rescue',nodes:[n('entry','entry'),n('hello','dialogue',{text:'Will you help?'}),n('choice','choice',{text:'Choose.',choices:[{id:'yes',label:'Yes'},{id:'no',label:'No'}]}),n('fight','battle',{ref:'slime'}),n('flag','set_flag',{flag:flag.id}),n('prize','reward',{rewards:{xp:5,coins:10}}),n('end','end')],edges:[e('entry','next','hello'),e('hello','next','choice'),e('choice','yes','fight'),e('choice','no','end'),e('fight','victory','flag'),e('fight','defeat','end'),e('fight','retreat','end'),e('flag','next','prize'),e('prize','next','end')],bindings:[{kind:'npc',ref:'scout',entry:'entry'}]});
function fixture(){const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE quest_characters(id TEXT PRIMARY KEY,name TEXT,state TEXT,revision INTEGER)');let time=100;const c={id:'alice'},s={flowVersion:1,fullDungeon:{flags:{school_graduated:true}}};db.prepare('INSERT INTO quest_characters VALUES (?,?,?,?)').run(c.id,'Alice',JSON.stringify(s),0);const p={npcs:{scout:{id:'scout'}},monsters:{slime:{id:'slime'}},quests:{},orbs:{}};const live={published:()=>p,view:()=>({compiledSprites:[],assets:[],equipment:[]}),bundle:()=>{}};const calls=[],options={live,world:{catalog:()=>[]},enabled:true,now:()=>time++,adapters:{battle:()=>{calls.push('battle');s.run={id:'encounter'};return 'encounter';},reward:(c,s,n,d,r)=>calls.push(r)}};let flows=createStoryFlows(db,options);flows.gm({action:'flow_flag_save',entry:flag,revision:0},'gm');const publish=(entry=story(),revision=0)=>flows.gm({action:'flow_publish',id:entry.id,entry,revision},'gm');const choose=(choice='')=>{const v=flows.snapshot(c,s);flows.act(c,s,{flow_run:v.id,flow_step:v.step,choice});};return {db,c,s,calls,p,publish,choose,get flows(){return flows;},restart(){flows=createStoryFlows(db,options);},close(){db.close();}};}
test('false defaults and authored flags preserve engine-owned achievements',()=>{const state={fullDungeon:{flags:{school_graduated:true}}};assert.equal(storyFlagsMatch(state,{all:['story_rescued']}),false);assert.equal(storyFlagsMatch(state,{none:['story_rescued']}),true);setStoryFlag(state,flag.id,true,[flag]);assert.equal(storyFlagsMatch(state,{all:[flag.id],any:['missing',flag.id]}),true);setStoryFlag(state,flag.id,false,[flag]);assert.equal(state.fullDungeon.flags.school_graduated,true);assert.throws(()=>setStoryFlag(state,'school_graduated',false,[{id:'school_graduated'}]),/Engine/);});
test('validator rejects missing ports, forged flags, unknown links and automatic cycles',()=>{const s=story();s.edges.pop();assert.throws(()=>validateFlow(s,{flags:[flag],publish:true}),/Connect/);s.edges.push(e('prize','next','flag'));assert.throws(()=>validateFlow(s,{flags:[flag],publish:true}),/loop/);s.nodes.find(n=>n.id==='flag').flag='school_graduated';assert.throws(()=>validateFlow(s,{flags:[flag],publish:true}),/authored flag/);});
test('pinned flow survives publication/restart and settles battle and reward once',()=>{const f=fixture();try{f.publish();assert.equal(f.flows.start(f.c,f.s,'npc','scout'),true);const first=f.flows.snapshot(f.c,f.s);f.choose();assert.throws(()=>f.flows.act(f.c,f.s,{flow_run:first.id,flow_step:first.step}),/changed/);f.choose('yes');assert.deepEqual(f.calls,['battle']);const changed=story();changed.nodes.find(n=>n.id==='prize').rewards.coins=999;f.publish(changed,1);f.restart();f.flows.resume(f.c,f.s);assert.equal(f.calls.length,1);f.flows.settled(f.c,f.s,'wrong','win');f.s.run=null;f.flows.resume(f.c,f.s);assert.equal(f.calls.length,1);f.flows.settled(f.c,f.s,'encounter','win');f.s.pendingDefeat={};f.flows.resume(f.c,f.s);assert.equal(f.calls.length,1);delete f.s.pendingDefeat;f.flows.resume(f.c,f.s);assert.equal(f.s.fullDungeon.flags.story_rescued,true);assert.equal(f.calls.length,2);f.flows.resume(f.c,f.s);f.flows.settled(f.c,f.s,'encounter','win');assert.equal(f.calls.length,2);assert.equal(f.flows.start(f.c,f.s,'npc','scout'),false);}finally{f.close();}});
test('choices revalidate current flags without replacing an open page',()=>{const f=fixture();try{const d=story();d.nodes.find(n=>n.id==='choice').choices[0].conditions={all:[flag.id]};f.publish(d);f.flows.start(f.c,f.s,'npc','scout');f.choose();assert.throws(()=>f.choose('yes'),/no longer available/);f.s.fullDungeon.flags[flag.id]=true;f.choose('yes');assert.equal(f.calls[0],'battle');}finally{f.close();}});
test('preview has no side effects and flags remain private to each character',()=>{const f=fixture();try{f.publish();const preview=f.flows.gm({action:'flow_preview',entry:story(),node:'fight',outcome:'victory',flags:{}},'gm');assert.equal(preview.flags[flag.id],true);assert.equal(f.s.fullDungeon.flags[flag.id],undefined);assert.equal(f.calls.length,0);f.s.flowVersion=0;assert.throws(()=>f.flows.start(f.c,f.s,'npc','scout'),/Update/);f.s.flowVersion=1;f.flows.start(f.c,f.s,'npc','scout');assert.equal(f.flows.snapshot({id:'bob'},f.s),null);}finally{f.close();}});
test('defeat and retreat never award victory flags',()=>{for(const outcome of ['defeat','flee']){const f=fixture();try{f.publish();f.flows.start(f.c,f.s,'npc','scout');f.choose();f.choose('yes');f.flows.settled(f.c,f.s,'encounter',outcome);f.s.run=null;f.flows.resume(f.c,f.s);assert.equal(f.s.fullDungeon.flags[flag.id],undefined);assert.equal(f.calls.length,1);}finally{f.close();}}});

test('imported choice requirements reject undefined authored flags',()=>{const d=story();d.nodes.find(n=>n.id==='choice').choices[0].requirements=[{flags:{all:['story_missing']}}];assert.throws(()=>validateFlow(d,{flags:[flag],publish:true}),/Unknown story flag/);});

test('an open NPC offer cannot switch to a newly published story',()=>{const f=fixture();try{f.publish();const review=f.flows.review(f.c,f.s,'npc','scout');assert.ok(review);f.publish(story(),1);assert.throws(()=>f.flows.start(f.c,f.s,'npc','scout',review),/offer changed/);assert.equal(f.flows.active(f.c),null);}finally{f.close();}});

test('changed flag reaction invalidates an NPC offer without starting another branch',()=>{const f=fixture();try{f.p.npcs.scout.story_reactions=[{conditions:{all:[flag.id]},entry:'hello'}];f.publish();const review=f.flows.review(f.c,f.s,'npc','scout');f.s.fullDungeon.flags[flag.id]=true;assert.throws(()=>f.flows.start(f.c,f.s,'npc','scout',review),/offer changed/);assert.equal(f.flows.active(f.c),null);}finally{f.close();}});

const pietyStory=(piety={op:'gte',value:50,god:''})=>({id:'rescue',name:'Piety gate',nodes:[n('entry','entry'),n('intro','dialogue',{text:'Approach the shrine.'}),n('piety','piety_check',{piety}),n('match','dialogue',{text:'Welcome, faithful traveler.'}),n('no_match','dialogue',{text:'Return when you are ready.'}),n('end','end')],edges:[e('entry','next','intro'),e('intro','next','piety'),e('piety','match','match'),e('piety','no_match','no_match'),e('match','next','end'),e('no_match','next','end')],bindings:[{kind:'npc',ref:'scout',entry:'entry'}]});
test('piety gates use current authoritative faith and both inclusive threshold branches',()=>{
 const god=flowFaithCatalog.gods[0].id;
 for(const [faith,expected] of [[undefined,'no_match'],[{god,piety:49},'no_match'],[{god,piety:50},'match'],[{god,piety:100},'match']]){const f=fixture();try{f.publish(pietyStory());f.flows.start(f.c,f.s,'npc','scout');f.s.faith=faith;f.s.loadout={faith:{god,piety:100},player_info:{piety:100}};f.choose();assert.equal(f.flows.snapshot(f.c,f.s).node,expected);assert.deepEqual(f.s.faith,faith);}finally{f.close();}}
 assert.equal(pietyMatches({}, {op:'eq',value:0,god:''}),true);
 assert.equal(pietyMatches({faith:{god,piety:20}},{op:'lte',value:20,god}),true);
 assert.equal(pietyMatches({faith:{god:flowFaithCatalog.gods[1].id,piety:100}},{op:'gte',value:50,god}),false);
 assert.equal(pietyMatches({}, {op:'lte',value:100,god}),false);
});
test('piety validation rejects forged patrons, thresholds and automatic loops',()=>{
 for(const piety of [{god:'constructor'},{god:'missing'},{value:-1},{value:101},{value:1.5},{value:'50'},{op:'run'}])assert.throws(()=>validateFlow(pietyStory(piety),{publish:true}),/piety threshold/);
 const d=pietyStory();d.edges.find(v=>v.from==='piety'&&v.port==='match').to='piety';assert.throws(()=>validateFlow(d,{publish:true}),/loop/);
});
test('piety preview is isolated and an active run pins the authored threshold across restart',()=>{
 const f=fixture(),god=flowFaithCatalog.gods[0].id;try{const d=pietyStory({op:'gte',value:50,god});f.publish(d);const before=JSON.stringify(f.s);
 const preview=faith=>f.flows.gm({action:'flow_preview',entry:d,node:'piety',faith},'gm');assert.equal(preview({god,piety:50}).node.id,'match');assert.equal(preview({god,piety:49}).node.id,'no_match');assert.equal(JSON.stringify(f.s),before);
 f.flows.start(f.c,f.s,'npc','scout');f.publish(pietyStory({op:'gte',value:90,god}),1);f.restart();f.s.faith={god,piety:60};f.choose();assert.equal(f.flows.snapshot(f.c,f.s).node,'match');
 }finally{f.close();}
});
